### ISSUE TITLE
Canvas layout ids autogeneration

### ISSUE THREAD

**Issue by 95kach** [capsulajs/capsulahub-extensions#18]
## General description

Canvas web component should auto-generate ids for each node in layout taken from config

#### Prerequisites

Currently, we have ids in the layout:
https://github.com/capsulajs/capsulahub-extensions/blob/develop/packages/canvas/cypress/fixtures/layout.js

We want not to persist IDs for each node of layout in configuration, the goal it's to take layout config and generate IDs for each node in layout.

id - random 3 chars string `dj3`, `jjf4` etc.

for the generation of id, you can use something like:

```
export const guid = (n = 3) => {
  const possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let text = '';
  for (let i = 0; i < n; i++) {
    text += possible.charAt(Math.floor(Math.random() * possible.length));
  }
  return text;
};
```

## API

Should be updated interfaces of component props. (remove id field).

#### Design description

- [ ] Is it backward compatible ?
- [ ] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

## Test cases

Not yet..

## Ready for implementation

- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Product owner
- [ ] Discussed with Technical lead

## Definition of Done

- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes

## RoadMap

Continue improvement of base components.
