### ISSUE TITLE
Configuration service extension

### ISSUE THREAD

**Issue by 95kach** [capsulajs/capsulahub-extensions#19]
## General description

Bootstrap for configuration service

#### Prerequisites

Links to any external dependency for this feature

#### Design description

A clear and concise description of the design proposition.

- [ ] Is it backward compatible ?
- [ ] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Changes

Provide link to a PR or code snippet of old and new API.

#### Consideration

List of everything to consider before writing test cases.

- [ ] Does the suggested changes impact the current behaviour ?
  
- [ ] Does the suggested changes are specific to some devices/browsers/environments
  
- [ ] Does the suggested changes require to add new dependencies to the package ?
  

## Test cases

Link to the PR with test cases, that are written in _**[Gherkin Syntax](https://docs.cucumber.io/gherkin/reference/)**_ and cover all the possible scenarios.

## Key Performance Indicator (KPI) Definition

A clear target that can be measured by the change.

_**Example:** reduce bundle size by X%._

## Ready for implementation

- [x] External dependencies have been resolved
- [x] API has been approved
- [x] Test cases have been prepared
- [x] Discussed with Product owner
- [x] Discussed with Technical lead

## Definition of Done

- [x] Maintainer review
- [x] All tests are implemented 
- [x] Manual QA
- [x] Documentation
- [x] Release notes
- [x] KPI has been reached

## RoadMap

In case there is more than one mergeable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.

**Comment by stephanebenayoun** [comment]
I see that a PR was merged already but the issue was not updated, is it done ?
