### ISSUE TITLE
Set CI/CD

### ISSUE THREAD

**Issue by MikeSquall** [capsulajs/capsulahub-extensions#23]
## General description
This repository have to be set in order to be able to use Travis CI to:
- build the app
- check the linting
- run the tests
- generate the documentation
- deploy the app on a CDN

Travis CI should have these variables set:
- [x] AWS_ACCESS_KEY_ID
- [x] AWS_SECRET_ACCESS_KEY
- [x] CF_BASE_URL
- [x] GH_ACCESS_TOKEN  
- [x] GH_USER 
- [x] PUBLIC_URL 
- [x] S3_BUCKET 
- [x] S3_REGION

## Ready for implementation
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented 
- [x] Manual QA
- [x] Documentation
- [x] Release notes

## RoadMap

In case there is more than one mergeable point you can specify it here.
