### ISSUE TITLE
Generate unique mountPoint for mounting React component in WebComponent

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulahub-extensions#32]
## General description

Each mount point should be generated automatically and be unique, cause it's only internal logic and we want to avoid naming collisions.

#### Consideration

List of everything to consider before writing test cases.

- [ ] Does the suggested changes impact the current behaviour ?
  
- [ ] Does the suggested changes are specific to some devices/browsers/environments
  
- [x] Does the suggested changes require to add new dependencies to the package ?
  

## Ready for implementation

- [ ] Discussed with Product owner
- [ ] Discussed with Technical lead

## Definition of Done

- [ ] Maintainer review
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes

## RoadMap

In case there is more than one mergeable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.
