### ISSUE TITLE
Request Form

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulahub-extensions#4]
## General description
Need to wrap [Request Form from here](https://github.com/capsulajs/capsulahub-ui/tree/develop/src/components/request-form) into the new web component to use it in the workspace.

A user will have to provide a selected service and a selected method (both of them will be included in the **selectedMethodPath** prop). (This data will be taken from **MethodSelectorService**)
Then he will be able to use editor to provide the request for this method and submit this request (if a method has a few args, a user can use a few editors to prepare all the args. Later the editor will automatically set the amount of editors, that are appropriate to the amount of args that the method requests). 
User can use JSON and JS modes. 
In JS mode the value that he eventually **returns** will be treated as an argument value. 
After the args are received from the editor, **Invoker** service will be used to call the method with the selected method and receive a single response from it (if it's promise) or to open a subscription (if this is observable).

#### Prerequisites
Capsulahub-UI: [Request Form](https://github.com/capsulajs/capsulahub-ui/tree/develop/src/components/request-form)
## API
```
interface SubmittedData {
  language: string;
  requestArgs: string[];
}

interface RequestFormUIProps {
  onSubmit: (submittedData: SubmittedData) => void; // callback on submit
  content: {
    language: string; // language of all the editors in the form - default to _**javascript**_
    requestArgs: string[] | string; // the input of each editor in the form. If a string is provided - the same value will be applied for each editor. default to **_"return {};"_**
  };
  selectedMethodPath: string; // selectedService/selectedMethodInTheService - default to **_""_**
}

interface RequestForm extends HTMLElement {
  setContent(setContentRequest: { language: 'string', requestArgs: string[] | string }) => void
}

```
#### Design description

A clear and concise description of the design proposition.

- [x] Is it backward compatible ?
- [ ] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Changes

Provide link to a PR or code snippet of old and new API.

#### Consideration
List of everything to consider before writing test cases.

- [ ] Does the suggested changes impact the current behaviour ?

- [ ] Does the suggested changes are specific to some devices/browsers/environments

- [ ] Does the suggested changes require to add new dependencies to the package ?

## Test cases

Link to the PR with test cases, that are written in _**[Gherkin Syntax](https://docs.cucumber.io/gherkin/reference/)**_ and cover all the possible scenarios.

[https://github.com/capsulajs/web-components/pull/10](https://github.com/capsulajs/web-components/pull/10)

## Key Performance Indicator (KPI) Definition

A clear target that can be measured by the change.

_**Example:** reduce bundle size by X%._

## Ready for implementation
- [x] External dependencies have been resolved
- [x] API has been approved
- [x] Test cases have been prepared
- [ ] Discussed with Product owner
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented 
- [x] Manual QA
- [x] Documentation
- [ ] Release notes
- [ ] KPI has been reached

## RoadMap

In case there is more than one mergeable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.
