### ISSUE TITLE
Migration UI components from JS to TS

### ISSUE THREAD

**Issue by 95kach** [capsulajs/capsulahub-extensions#48]
## General description

As a developer, I want to have the possibility to reuse UI components in external TS projects.

- [x] Is it backward compatible ?
- [ ] Adds new API
- [x] Changes existing API
- [ ] Removes existing API

#### Changes

https://github.com/capsulajs/capsulahub/tree/develop/packages/ui

#### Consideration

- [ ] Does the suggested changes impact the current behaviour ?
  
- [x] Does the suggested changes are specific to some devices/browsers/environments
  
- [x] Does the suggested changes require to add new dependencies to the package ?
  types

## Test cases

- Already have in extensions packages.
- Don't think that duplication of them is good.

## Ready for implementation

- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Product owner
- [ ] Discussed with Technical lead

## Definition of Done

- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes
- [ ] KPI has been reached

## RoadMap

JS -> Typescript

**Comment by stephanebenayoun** [comment]
Can you be more specific about components that you would like to use ?

We don't plan to rewrite the UI Components, our road map will be closer to use external UI library (like https://github.com/mui-org/material-ui) and customise it to CapsulaHub look and feel.

If you're talking about widgets that are a composition of several ui components (like Logger or Request Form), they will probably be rewritten using the chosen UI library but we cannot provide timeline for this right now.
