### ISSUE TITLE
Stable version of capsulahub

### ISSUE THREAD

**Issue by 95kach** [capsulajs/capsulahub-extensions#49]
## General description

As a developer, I want to have the possibility to use the capsulahub according to the documentation without any unexpected side effects.

I need to know from which version I can use capsulahub as a stable product.

CLI, documentation or examples of usage should be realistic and ready for use in production.

## Behavior

It should work.

## Test cases

No

## Ready for implementation

- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Product owner
- [ ] Discussed with Technical lead

## Definition of Done

- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes

## RoadMap

Way to success.
