### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulahub-extensions#6]
## General description
Create a canvas web component and layout service that will integrate it with a workspace.

- [x] Discuss and finalize layout API. 
- [x] Wrap canvas into web component (basic example).

#### Prerequisites
[Canvas](https://github.com/capsulajs/capsulahub-ui/tree/develop/src/components/canvas)
## API
[Canvas Example](https://github.com/capsulajs/capsulahub-ui/blob/develop/stories/Canvas.stories.js#L58)

```
interface Element {
  id: string;
  type: 'element';
  flex: number;
  activeTabIndex: number;
  tabs: Tab[];
}

interface Container {
  id: string;
  type: 'container';
  flex: number;
  orientation:  'horizontal' | 'vertical';
  nodes: [<Container | Element>, <Container | Element>]
}

interface Tab {
  id: string;
  name: string;
  content: HTMLElement;  //<web-logger id="bla"></web-logger>
}

const type Layout = Container | Element;

interface CanvasProps {
  layout: Layout;
  onUpdate: (newLayout: Layout) => void;
}
```
#### Design description

A clear and concise description of the design proposition.

- [ ] Is it backward compatible ?
- [x] Adds new API
- [x] Changes existing API
- [ ] Removes existing API

#### Changes

Provide link to a PR or code snippet of old and new API.

#### Consideration
List of everything to consider before writing test cases.

- [ ] Does the suggested changes impact the current behaviour ?

- [ ] Does the suggested changes are specific to some devices/browsers/environments

- [ ] Does the suggested changes require to add new dependencies to the package ?

## Test cases

Link to the PR with test cases, that are written in _**[Gherkin Syntax](https://docs.cucumber.io/gherkin/reference/)**_ and cover all the possible scenarios.

## Key Performance Indicator (KPI) Definition

A clear target that can be measured by the change.

_**Example:** reduce bundle size by X%._

## Ready for implementation
- [ ] External dependencies have been resolved
- [x] API has been approved
- [x] Test cases have been prepared
- [ ] Discussed with Product owner
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented 
- [x] Manual QA
- [x] Documentation
- [ ] Release notes
- [ ] KPI has been reached

## RoadMap

In case there is more than one mergeable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.
